version: "3.3"

services:
  frontend:
    image: intkbv/utrechtsciencepark-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      # RAZZLE_API_PATH: http://backend:8080/Plone
      # API_PATH: https://www.cihanandac.net
      # PUBLIC_URL: https://www.cihanandac.net
    depends_on:
      - backend
    networks:
      - backend
    ports:
      - 3000:3000
    deploy:
      replicas: 2

  stage-frontend:
    image: intkbv/utrechtsciencepark-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_API_PATH: http://backend:8080/Plone
      # API_PATH: https://www.cihanandac.net
      # PUBLIC_URL: https://www.cihanandac.net
    depends_on:
      - backend
    networks:
      - backend
    ports:
      - 3001:3000
    deploy:
      replicas: 1

  backend:
    image: intkbv/utrechtsciencepark-backend:latest
    environment:
      SITE: Plone
      ZEO_ADDRESS: zeo:8100
      # ADDONS: "collective.volto.dropdownmenu collective.volto.formsupport collective.volto.cookieconsent plone.formwidget.recaptcha"
    volumes:
      - cache:/data
    networks:
      - backend
    ports:
      - 8080:8080

  zeo:
    image: plone/plone-zeo:latest
    volumes:
      - /var/local/utrechtsciencepark/data:/data
    ports:
      - 8100:8100
    networks:
      - backend

volumes:
  cache: {}

networks:
  backend:
    driver: overlay
